[package]
edition = "2021"
name = "nativeToken"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-contract-standards = "3.1.0"
near-sdk = "3.1.0"
